[package]
name = "todomvc"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
edition = "2018"

[dependencies]
strum = { version = "0.13" }
strum_macros = { version = "0.13" }
serde = { version = "1" }
serde_derive = { version = "1" }
yew = { version = "0.10.0" }
